### ISSUE TITLE
User can view a list of programs

### ISSUE THREAD

**Issue by farookisonfire** [farookkhan/ubuntu#3]
# Motivation
We want users to be able to view a list of all programs.

# Implementation Details
Use Semantic-UI Table Component for the list of programs.

# Task List
- [x] Create the Programs container component
- [x] Create ProgramList component
- [x] Create ProgramFilters component
- [x] Create Programs Reducer
- [x] Configure Redux Store
- [x] Create InitialState

**Comment by farookisonfire** [comment]
![screen shot 2017-07-04 at 11 51 58 am](https://user-images.githubusercontent.com/19194235/27840628-65dd68d8-60af-11e7-88cd-b3a2df7e1d43.png)
